# Generated by Django 3.1 on 2021-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.FileField(upload_to='file'),
        ),
    ]
